[tool.poetry]
name = "arcs_service"
version = "0.1.0"
description = "ArcsService é um microsserviço do sistema ARCS, responsável por gerenciar toda regra de aplicação"
repository = "https://github.com/teltec-arcs/arcs-service"
authors = ["Tiago Pereira <tiago.pereira@teltecsolutions.com.br>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
bcrypt = "^4.2.0"
google-auth = "^2.36.0"
pytest = "8.3.3"

[tool.poetry.group.prod.dependencies]
arcs-lib-pca = { path = "../arcs-lib-pca/" }
gunicorn = "^23.0.0"

[tool.poetry.group.hml.dependencies]
arcs-lib-pca = { path = "../arcs-lib-pca/" }
gunicorn = "^23.0.0"

[tool.poetry.group.dev.dependencies]
arcs-lib-pca = { path = "../arcs-lib-pca/", develop=true}
tox = "^4.15.0"
faker = "^33.0.0"
colorlog = "^6.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
