from .access_profiles import AccessProfilesController
from .app_clients import AppClientsController
from .permissions import PermissionsController
from .services import ServicesController
from .auth.controller import AuthController
from .registers.controller import RegisterController
from .groups.controller import GroupController
from .logout.controller import LogoutController
from .authorize.controller import AuthorizeController
from .guests.controller import GuestController
from .persons.controller import PersonController
from .profiles.controller import ProfileController
from .groups.controller import GroupController
from .subgroups.controller import SubGroupController
from .invite.controller import InviteController
from .reset_password import ResetPasswordController
from .fia_card_types import FiaCardTypeController
from .cba_card_types import CBACardTypeController
from .contact_types import ContactTypeController
from .dashboards import DashboardsController
from .refresh_token import RefreshTokenController
from .users import UserController
from .key_contacts import KeyContactsController
from .personal_teams import PersonalTeamController
from .technical_teams import TechnicalTeamController
from .users import UserController
from .pilots import PilotController
from .user_guests import UserGuestController
