name: Build, Deploy and Settings

# Trigger conditions
on:
  push:
    branches:
      [ hml ]
    paths:
      - '**'
      - '.github/workflows/build-deploy-hml.yml'
  workflow_dispatch:

env:
  AZURE_PATH_PROVIDERS: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RG_NAME_HML }}/providers
  CONTAINER_APP_NAME: "${{ github.event.repository.name }}-hml"  # Nome do repositório sem 'owner/'
  CONTAINER_APP_SOURCE_ID: "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RG_NAME_HML }}/providers/Microsoft.App/containerApps/${{ github.event.repository.name }}-hml"
  CONTAINER_PORT: 8000
  #Passar essa variáveis para azure app configuration
  MICROSERVICE_INTERNAL_URL: https://${{ github.event.repository.name }}-hml.greenwater-27be5db9.eastus2.azurecontainerapps.io
  ARCS_SERVICE_INTERNAL_URL: https://arcs-service-hml.greenwater-27be5db9.eastus2.azurecontainerapps.io
  MICROSERVICE_EXTERNAL_URL: https://arcs-apim-hml.azure-api.net${{vars.APIM_API_ROUTE_PATH}}
  ARCS_SERVICE_EXTERNAL_URL: https://arcs-apim-hml.azure-api.net/arcs

jobs:
  build:
    runs-on: ubuntu-latest
    environment: HML
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds:  ${{ secrets.AZURE_CREDENTIALS_HML }}

      - name: Login to ACR and configure az
        run: |
          az acr login --name ${{ secrets.ACR_NAME_HML }}
          az account set -s ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az configure --defaults group=${{ secrets.RG_NAME_HML }}
      
      - name: Generate .env File of secrets and vars
        id: generate_env_file
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          REMOVE_SUFIX: _HML
        run: |
          source ./infra/arcs.sh
          convert_json_to_env '${{ toJSON(secrets) }}'
          convert_json_to_env '${{ toJSON(vars) }}'
          convert_json_to_env '${{ toJSON(env) }}'
      
      - name: Build and push container image to registry
        run: |
          docker build \
            --build-arg TOKEN_PKG_LIB_GITHUB=${{ secrets.TOKEN_PKG_LIB_GITHUB }} \
            -t ${{ secrets.ACR_NAME_HML }}.azurecr.io/${{ github.event.repository.name }}:${{ github.sha }} \
            -f ./infra/Dockerfile.hml .
          docker push ${{ secrets.ACR_NAME_HML }}.azurecr.io/${{ github.event.repository.name }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: HML
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds:  ${{ secrets.AZURE_CREDENTIALS_HML }}

      - name: Set subscription and group default
        run: |
          az acr login --name ${{ secrets.ACR_NAME_HML }}
          az account set -s ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az configure --defaults group=${{ secrets.RG_NAME_HML }}
          az extension add --name containerapp --upgrade
          az extension add --name serviceconnector-passwordless --upgrade

      - name: Check if ${{ env.CONTAINER_APP_NAME }} exists in Azure container apps
        run: |
          if az containerapp show --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ secrets.RG_NAME_HML }} --query 'properties.provisioningState' -o tsv; then
            echo "Container App ${{ env.CONTAINER_APP_NAME }}: exists."
            echo "aca_exists=true" >> $GITHUB_ENV
          else
            echo "Container App ${{ env.CONTAINER_APP_NAME }}: does not exist."
            echo "aca_exists=false" >> $GITHUB_ENV
          fi

      - name: Create Container App
        if: env.aca_exists == 'false'
        run: |
          az containerapp create \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.RG_NAME_HML }} \
            --environment ${{ secrets.ARCS_ENV_APP_HML }} \
            --image ${{ secrets.ACR_NAME_HML }}.azurecr.io/${{ github.event.repository.name }}:${{ github.sha }} \
            --ingress external \
            --registry-server ${{ secrets.ACR_NAME_HML }}.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME_HML }} \
            --registry-password ${{ secrets.ACR_PASSWORD_HML }} \
            --bind redisservicehml \
            --user-assigned ${{ env.AZURE_PATH_PROVIDERS }}/Microsoft.ManagedIdentity/userAssignedIdentities/${{ secrets.AZURE_MANAGED_IDENTITY_NAME_HML }} \
            --target-port ${{ env.CONTAINER_PORT }} \
            --min-replicas 1 \
            --workload-profile-name simulate_prod
      
      - name: Update Container App
        if: env.aca_exists == 'true'
        run: |
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.RG_NAME_HML }} \
            --bind redisservicehml \
            --image ${{ secrets.ACR_NAME_HML }}.azurecr.io/${{ github.event.repository.name }}:${{ github.sha }} \
            --min-replicas 1 \
            --workload-profile-name simulate_prod
  
      - name: Assign managed identity to Container App
        run: |
          az containerapp identity assign \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.RG_NAME_HML }} \
            --user-assigned ${{ env.AZURE_PATH_PROVIDERS }}/Microsoft.ManagedIdentity/userAssignedIdentities/${{ secrets.AZURE_MANAGED_IDENTITY_NAME_HML }}

      - name: Validate if Container App is running
        run: |
          ATTEMPTS=0
          MAX_ATTEMPTS=3
          SLEEP_INTERVAL=30
      
          while [[ $ATTEMPTS -lt $MAX_ATTEMPTS ]]; do
            CONTAINER_APP_STATUS=$(az containerapp show --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ secrets.RG_NAME_HML }} --query 'properties.provisioningState' -o tsv)
      
            if [[ "$CONTAINER_APP_STATUS" == "Succeeded" ]]; then
              echo "Container App is running successfully."
              break
            elif [[ "$CONTAINER_APP_STATUS" == "InProgress" ]]; then
              ATTEMPTS=$((ATTEMPTS+1))
              echo "Attempt $ATTEMPTS/$MAX_ATTEMPTS: Container App is still in progress. Waiting $SLEEP_INTERVAL seconds before retrying..."
              sleep $SLEEP_INTERVAL
            else
              echo "Container App is not running correctly. Current status: $CONTAINER_APP_STATUS"
              echo "Fetching logs for Container App..."
              az containerapp logs show --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ secrets.RG_NAME_HML }} --tail 100
              exit 1  # Fail the job if the container app is not running correctly
            fi
          done
      
          if [[ "$CONTAINER_APP_STATUS" != "Succeeded" ]]; then
            echo "Container App failed to reach 'Succeeded' status after $MAX_ATTEMPTS attempts."
            exit 1  # Fail the job if the container app never reaches 'Succeeded'
          fi

      - name: Create connection to storage-blob
        if: env.aca_exists == 'false'
        run: |
            az containerapp connection create storage-blob \
              --target-id ${{ env.AZURE_PATH_PROVIDERS }}/Microsoft.Storage/storageAccounts/${{ secrets.STORAGE_NAME_HML }}/blobServices/default \
              --source-id ${{ env.CONTAINER_APP_SOURCE_ID }} \
              --container ${{ env.CONTAINER_APP_NAME }} \
              --connection arcsstorage \
              --client-type python \
              --service-principal client-id=${{ secrets.AZURE_CLIENT_ID_HML }} secret=${{ secrets.AZURE_CLIENT_SECRET_HML }}

      - name: Create connection to keyvault
        if: env.aca_exists == 'false'
        run: |
          az containerapp connection create keyvault \
            --target-id ${{ env.AZURE_PATH_PROVIDERS }}/Microsoft.KeyVault/vaults/${{ secrets.ARCS_KV_NAME_HML }} \
            --source-id ${{ env.CONTAINER_APP_SOURCE_ID }} \
            --container ${{ env.CONTAINER_APP_NAME }} \
            --connection arcs_kv \
            --client-type python \
            --service-principal client-id=${{ secrets.AZURE_CLIENT_ID_HML }} secret=${{ secrets.AZURE_CLIENT_SECRET_HML }}

      - name: Create connection to postgres-flexible
        if: env.aca_exists == 'false'
        run: |
          az containerapp connection create postgres-flexible \
            --target-id ${{ env.AZURE_PATH_PROVIDERS }}/Microsoft.DBforPostgreSQL/flexibleServers/${{ secrets.ARCS_POSTGRES_SERVER_HML }}/databases/${{ secrets.POSTGRES_DB }} \
            --source-id ${{ env.CONTAINER_APP_SOURCE_ID }} \
            --container ${{ env.CONTAINER_APP_NAME }} \
            --connection user_${{ secrets.POSTGRES_DB }} \
            --client-type python \
            --service-principal client-id=${{ secrets.AZURE_CLIENT_ID_HML }} object-id=${{ secrets.AZURE_CLIENT_OBJECT_ID_HML }} secret=${{ secrets.AZURE_CLIENT_SECRET_HML }} \
            --yes

      - name: Create connection to webpubsub
        if: env.aca_exists == 'false'
        run: |
          az containerapp connection create webpubsub \
            --target-id ${{ env.AZURE_PATH_PROVIDERS }}/Microsoft.SignalRService/WebPubSub/${{ secrets.ARCS_PUBSUB_HML }} \
            --source-id ${{ env.CONTAINER_APP_SOURCE_ID }} \
            --container ${{ env.CONTAINER_APP_NAME }} \
            --connection arcs_pubsub \
            --client-type python \
            --service-principal client-id=${{ secrets.AZURE_CLIENT_ID_HML }} secret=${{ secrets.AZURE_CLIENT_SECRET_HML }}
      
  settings:
    needs: deploy
    runs-on: ubuntu-latest
    environment: HML2
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds:  ${{ secrets.AZURE_CREDENTIALS_HML }}

      - name: Set subscription and group default
        run: |
          az account set -s ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az configure --defaults group=${{ secrets.RG_NAME_HML }}
          az extension add --name containerapp --upgrade
          az extension add --name serviceconnector-passwordless --upgrade

      # - name: Get url of container
      #   run: |
      #     MICROSERVICE_INTERNAL_URL="$(az containerapp show --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ secrets.RG_NAME_HML }} --query 'properties.configuration.ingress.fqdn' -o tsv)"
      #     echo "MICROSERVICE_INTERNAL_URL=https://$MICROSERVICE_INTERNAL_URL" >> $GITHUB_ENV

      #     ARCS_SERVICE_INTERNAL_URL="$(az containerapp show --name arcs-service-hml --resource-group ${{ secrets.RG_NAME_HML }} --query 'properties.configuration.ingress.fqdn' -o tsv)"
      #     echo "ARCS_SERVICE_INTERNAL_URL=https://$ARCS_SERVICE_INTERNAL_URL" >> $GITHUB_ENV
          
      #     LATEST_REVISION_NAME="$(az containerapp show --name arcs-service-hml --resource-group ${{ secrets.RG_NAME_HML }} --query 'properties.latestRevisionName' -o tsv)"
      #     echo "LATEST_REVISION_NAME=$LATEST_REVISION_NAME" >> $GITHUB_ENV

      - name: Executing post_boot in the microservice
        run: |
          RESPONSE=$(curl -s -o /dev/stderr -w "%{http_code}" -X POST "${{ env.MICROSERVICE_INTERNAL_URL }}/lib/post_boot" \
            -H "Authorization: TOKEN ${{ secrets.SECRET_ARCS_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data-raw '{}')
            
          echo "Response body and status code:"
          echo "$RESPONSE"
          echo "Executed post_boot"
          
      - name: Check if API exists in API Management
        id: check_api
        run: |
          if az apim api show --resource-group ${{ secrets.RG_NAME_HML }} --service-name ${{ secrets.APIM_NAME_HML }} --api-id ${{ env.CONTAINER_APP_NAME }}; then
            echo "API ${{ env.CONTAINER_APP_NAME }}: exists."
            echo "api_exists=true" >> $GITHUB_ENV
          else
            echo "API ${{ env.CONTAINER_APP_NAME }}: does not exist."
            echo "api_exists=false" >> $GITHUB_ENV
          fi

      - name: Create endpoint in API Management
        if: env.api_exists == 'false'
        run: |
          az apim api create \
            --resource-group ${{ secrets.RG_NAME_HML }} \
            --service-name ${{ secrets.APIM_NAME_HML }} \
            --api-id ${{ env.CONTAINER_APP_NAME }} \
            --display-name "${{ vars.APIM_API_NAME_FRIENDLY }}" \
            --path "${{ vars.APIM_API_ROUTE_PATH }}" \
            --service-url "${{ env.MICROSERVICE_INTERNAL_URL }}" \
            --protocols ${{ vars.APIM_API_PROTOCOLS }} \
            --description "${{ vars.APIM_API_DESCRIPTION }}"

      - name: Update endpoint in API Management
        if: env.api_exists == 'true'
        run: |
          az apim api update \
            --resource-group ${{ secrets.RG_NAME_HML }} \
            --service-name ${{ secrets.APIM_NAME_HML }} \
            --api-id ${{ env.CONTAINER_APP_NAME }} \
            --display-name "${{ vars.APIM_API_NAME_FRIENDLY }}" \
            --path ${{ vars.APIM_API_ROUTE_PATH }} \
            --service-url "${{ env.MICROSERVICE_INTERNAL_URL }}" \
            --protocols ${{ vars.APIM_API_PROTOCOLS }} \
            --description "${{ vars.APIM_API_DESCRIPTION }}"

      - name: Import/Update API in APIM
        run: |
          az apim api import \
            --resource-group ${{ secrets.RG_NAME_HML }} \
            --service-name ${{ secrets.APIM_NAME_HML }} \
            --api-id ${{ env.CONTAINER_APP_NAME }} \
            --path "${{ vars.APIM_API_ROUTE_PATH }}" \
            --display-name "${{ vars.APIM_API_NAME_FRIENDLY }}" \
            --description "${{ vars.APIM_API_DESCRIPTION }}" \
            --service-url "${{ env.MICROSERVICE_INTERNAL_URL }}" \
            --specification-path ${{ github.workspace }}/infra/openapi.yml \
            --specification-format OpenApi \
            --protocols https

      - name: Send POST request to register microservice
        run: |
          echo "Sending POST request to register microservice..."
          
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "${{ env.MICROSERVICE_INTERNAL_URL }}/lib/register_microservice" \
            -H "Authorization: TOKEN ${{ secrets.SECRET_ARCS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}')
          
          BODY=$(echo "$RESPONSE" | head -n -1) # Obtém o corpo da resposta.
          STATUS_CODE=$(echo "$RESPONSE" | tail -n 1) # Obtém o código HTTP.
          
          echo "Response body:"
          echo "$BODY"
          
          echo "HTTP Status Code:"
          echo "$STATUS_CODE"